baseURL = "https://dropbyte.ch"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
[[menu.footer]]
URL = "http://learn.dropbyte.ch"
name = "QuickBytes"
weight = 4
[[menu.footer]]
URL = "https://dropbyte.ch/#contact"
name = "Contact"
weight = 5
[[menu.footer]]
URL = "https://dropbyte.ch/#pricing"
name = "Pricing"
weight = 3
[[menu.footer]]
URL = "https://dropbyte.ch/#portfolio"
name = "Services"
weight = 2
[[menu.footer]]
URL = "https://dropbyte.ch/#about"
name = "About"
weight = 1
[[menu.header]]
URL = "https://client.dropbyte.ch/login"
name = "Log In"
url = "https://client.dropbyte.ch/login"
weight = "6"
[[menu.header]]
URL = "https://dropbyte.ch/#pricing"
name = "Pricing"
url = ""
weight = 3
[[menu.header]]
URL = "https://dropbyte.ch/#contact"
name = "Contact"
weight = 4
[[menu.header]]
URL = "https://dropbyte.ch/#portfolio"
name = "Services"
weight = 2
[[menu.header]]
URL = "https://dropbyte.ch/#about"
name = "About"
weight = 1
[params]
googleTagManagerID = "GTM-000000"
homepage = ["showcase", "about", "client-and-work", "pricing", "contact", "newsletter"]
article = ["article"]
[params.footer]
copyright = "© DropByte and "
[params.footer.radity_logo]
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
x = "img/general/design-and-code-radity.png"
[params.logo]
text1 = "Drop"
text2 = "Byte"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
