baseURL = "https://dropbyte.ch"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
[[menu.footer]]
URL = "http://learn.dropbyte.ch"
name = "QuickBytes"
weight = 5
[[menu.footer]]
URL = "https://dropbyte.ch/#contact"
name = "Contact"
weight = 6
[[menu.footer]]
URL = "/premium"
name = "Premium"
weight = 3
[[menu.footer]]
URL = "/enterprise"
name = "Enterprise"
weight = 4
[[menu.footer]]
URL = "/services"
name = "Services"
weight = 2
[[menu.footer]]
URL = "/about"
name = "About"
weight = 1

[[menu.header]]
name = "Log In"
url = "https://client.dropbyte.ch/login"
weight = "6"
[[menu.header]]
name = "Services"
url = "/services"
weight = 3
# [[menu.header]]
# URL = "https://dropbyte.ch/#contact"
# name = "Contact"
# weight = 4
# [[menu.header]]
# URL = "/services"
# name = "Services"
# weight = 2
# [[menu.header]]
# parent = "Services"
# name = "QuickBytes"
# URL = "https://learn.dropbyte.ch"
# weight = 1
[[menu.header]]
URL = "/about"
name = "About"
weight = 1
[params]
googleTagManagerID = "GTM-000000"
homepage = ["showcase", "leads", "contact"]
article = ["article"]
form = ["form"]
about = ["about", "testimonial", "contact"]
services = ["client-and-work", "pricing", "leads", "contact"]
premium = ["premium-perks", "leads", "contact" ]
enterprise = ["enterprise-perks", "leads", "contact" ]
[params.footer]
copyright = "© DropByte and "
[params.footer.radity_logo]
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
x = "img/general/design-and-code-radity.png"
[params.logo]
text1 = "Drop"
text2 = "Byte"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
