---
new_page_extension: md
auto_deploy: false
admin_path: https://dropbyte.ch/admin
webhook_url: 
sections:
- type: heading
  label: PAGES
- type: document
  path: themes/raditian-free-hugo-theme/data/homepage.yml
  label: Home Page
- type: heading
  label: FILES
- type: directory
  path: ''
  label: dropbyte.ch
  create: all
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
