---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: config.toml
  label: config
- type: heading
  label: PAGES
- type: document
  path: data/homepage.yml
  label: Home
- type: document
  path: data/about.yml
  label: About
- type: document
  path: data/services.yml
  label: Services
- type: document
  path: data/premium.yml
  label: Premium
- type: document
  path: data/enterprise.yml
  label: Enterprise
- type: heading
  label: CONTENT
- type: directory
  path: content/quickbytes
  label: QuickBytes
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Content
  create: all
  match: "**/*"
- type: heading
  label: FILES
- type: directory
  path: ''
  label: dropbyte.ch
  create: all
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
